before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
services:
  - cassandra
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
matrix:
  exclude:
  - rvm: 2.0.0
    jdk: openjdk7
  - rvm: 2.0.0
    jdk: oraclejdk7
  - rvm: 1.9.3
    jdk: openjdk7
  - rvm: 1.9.3
    jdk: oraclejdk7
  - rvm: rbx-19mode
    jdk: openjdk7
  - rvm: rbx-19mode
    jdk: oraclejdk7
